# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by James Laurie

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [44]:
%pip install numpy
import numpy as np
np.random.randint(10, 32, size=(6,5))

Note: you may need to restart the kernel to use updated packages.


array([[27, 20, 28, 20, 10],
       [15, 15, 10, 14, 18],
       [29, 18, 28, 26, 16],
       [10, 19, 15, 31, 15],
       [13, 25, 24, 28, 24],
       [11, 19, 15, 11, 19]])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [3]:
len(np.arange(1, 50, 2, dtype=int))

25

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [4]:
np.linspace(4, 7, num=27)

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [7]:
np.random.random((5, 4))

array([[0.14104692, 0.91812632, 0.61247577, 0.82664568],
       [0.28678042, 0.71729383, 0.57017951, 0.54618601],
       [0.80848629, 0.0602572 , 0.40668214, 0.73095478],
       [0.23825877, 0.29608962, 0.59344024, 0.15566535],
       [0.29637787, 0.24728828, 0.69933322, 0.96189037]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [6]:
np.random.randint(5, 15, size=(5, 5))

array([[11, 12, 10,  5, 12],
       [13, 14,  8,  6,  5],
       [12,  5, 12, 12, 13],
       [14,  7,  9, 13,  6],
       [11, 13,  8,  7, 11]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [60]:
import random
np.zeros(random.randint(1,21), dtype='int32')


array([0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [59]:
np.ones((random.randint(1,21),random.randint(1,21)), dtype='float32')


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
      dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [61]:
ar = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6], [23,12,8,5,8]])
print(ar)
print(ar.dtype)
print(ar.shape)
print(type(ar))


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
int32
(5, 5)
<class 'numpy.ndarray'>


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [64]:
center = np.take(ar, ar.size // 2)
print(center)


3


#### 10. Print the all the elements of 3rd row of the matrix

In [23]:
third_row = ar[2]
print(third_row)


[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [24]:
fourth_col = ar[:, 3]
print(fourth_col)


[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [25]:
print(ar[[0, 0, -1, -1], [0, -1, 0, -1]])


[ 9 45 23  8]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [49]:
m1 = ar[3:5,0:2]
m2 = ar[0:2,2:4]
m3 = ar[2:5,2:5]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [50]:
flat_m1 = m1.flatten(order='C')
flat_m2 = m2.flatten(order='C')
flat_m3 = m3.flatten(order='C')

#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [54]:
vertical = np.concatenate((m1, m2), axis=0)
vertical

array([ 7,  8, 23, 12, 50, 34, 34, 65])

In [66]:
horizontal = np.concatenate((m1, m2), axis=1)
horizontal


array([[ 7,  8, 50, 34],
       [23, 12, 34, 65]])

#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [57]:
add = m1 + m2
subtract = m1 - m2
divide = m1 / m2


array([[0.14      , 0.23529412],
       [0.67647059, 0.18461538]])

#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [58]:
added = m1 + m3[1:3,0:2]
added

array([[13, 62],
       [31, 17]])

#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

#### 19. Perform the matrix multiplication between m3 and m4

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [75]:
runs_scored = np.array([
    ['MSD',54,60,10,65],
    ['Kholi',102,2,78,32],
    ['Rohit',3,110,1,92],
    ['Rahul',56,6,12,42],
    ['Dhawan',12,8,22,11]
])
balls_faced = np.array([
    ['MSD',50,42,22,78],
    ['Kholi',95,8,65,43],
    ['Rohit',9,100,7,101],
    ['Rahul',27,3,11,31],
    ['Dhawan',24,20,36,27]
])
balls_faced

balls = balls_faced[:,1:]
runs = runs_scored[:,1:]
ball1 = balls.astype("int32")
run1 = runs.astype("int32")

strike = run1/ball1 * 100
print(strike)

strike_mean = strike.mean(axis=1)

strike_mean_columns = strike_mean.reshape([5,1])
print(strike_mean_columns)

player = np.concatenate([balls,strike_mean_columns],axis=1)
ind = strike_mean.argsort() #ascend
final = player[ind,:][::-1]
print(final)
    

[[108.         142.85714286  45.45454545  83.33333333]
 [107.36842105  25.         120.          74.41860465]
 [ 33.33333333 110.          14.28571429  91.08910891]
 [207.40740741 200.         109.09090909 135.48387097]
 [ 50.          40.          61.11111111  40.74074074]]
[[ 94.91125541]
 [ 81.69675643]
 [ 62.17703913]
 [162.99554687]
 [ 47.96296296]]
[['27' '3' '11' '31' '162.99554686651462']
 ['50' '42' '22' '78' '94.91125541125541']
 ['95' '8' '65' '43' '81.69675642594859']
 ['9' '100' '7' '101' '62.17703913248468']
 ['24' '20' '36' '27' '47.96296296296296']]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [76]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
failed = 0
passed = 0


for n in marks:
    if n < 50:
        failed += 1
    else:
        passed += 1


print(f'The number of student who failed is {failed}')
print(f'The number of student who passed is {passed}')

The number of student who failed is 3
The number of student who passed is 7


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [85]:
new_marks = marks.copy()
mearcy_marks=np.where((new_marks>=45)& (new_marks<=49))
new_marks[mearcy_marks]=new_marks[mearcy_marks]+5
bouns_marks = np.where((new_marks>80)&(new_marks<=95))
new_marks[bouns_marks]=new_marks[bouns_marks]+5
new_marks1=np.where(new_marks>95)
new_marks[bouns_marks]=100
print("\n actual marks ",marks)
print("\n new Marks of student", new_marks)
actul_pass = (len(marks[np.where(marks>=50)])/len(marks))*100
new_mark_out= (len(new_marks[np.where(new_marks>=50)])/len(new_marks))*100
inc_percent = new_mark_out-actul_pass
print(inc_percent,"%")


 actual marks  [65 84 47 56 89 98 48 77 80 39]

 new Marks of student [ 65 100  52  56 100  98  53  77  80  39]
20.0 %


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [82]:
import time
x = range(1,60000)
y= range (1,60000)
out = []
st = time.time()
for i , j in zip(x,y):
    out.append((x[i-1]*x[i-1]+8)/y[i-1])
print((time.time()-st)*1000)


x_arr = np.arange(1,60000)
y_arr = np.arange(1,60000)
st_t=time.time()
out_arr = ((x_arr*x_arr)+8)/y_arr
print((time.time()-st_t)*1000)

73.80056381225586
0.9973049163818359
